FROM maven:3.8.8-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
RUN nvm clean packpge -DskipTests

FROM openjdk:17-jdk-slim
WORKDIR /app
COPY config.yaml /app/config.yaml
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]

